# Set to the lowest supported Python version.
target-version = "py311"

# Set the target line length for formatting.
line-length = 120

# Exclude a variety of commonly ignored directories.
extend-exclude = [
    "example/*.ipynb"
]

src = ["."]

[lint]
# Select and/or ignore rules for linting.
# Full list of available rules: https://docs.astral.sh/ruff/rules/
extend-select = [
    "B", # Flake8 bugbear
    "E", # Pycodestyle errors
    "F", # Pyflakes
    "I", # Isort
    "NPY", # Numpy
    "PT", # Pytest
    "RUF", # Ruff-specific rules
    "UP", # Pyupgrade
    "W", # Pycodestyle warnings
]
ignore = [
    "NPY002", # Replace legacy `np.random.rand` call with `np.random.Generator`
    "E731", # Do not assign a lambda expression, use a def
    "F403", # * import used; unable to detect undefined names
    "F405", # x may be undefined, or defined from star imports
    "B007", # Loop control variable `i` not used within loop body
    "UP006", # tuple, dict instead of Tuple, Dict
    "UP015", # Unnecessary mode argument in open
    "UP035", # typing.Tuple/Dict deprecated
    "PT018", # Assertion should be broken down into multiple parts
    "RUF002", # En dash
    "B028", #  No explicit `stacklevel` keyword argument found
]


[lint.pycodestyle]
max-line-length = 150 # Allow some flexibility in line lengths
max-doc-length = 150

[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true
