# This CI will check the package is installable and run some tests
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install package
        run: |
          pip install --upgrade pip
          pip install .[test]
          python -c "import NeSST"

      - name: run examples
        run: |
          cd example
          jupyter nbconvert --to python 'NeSST Guide.ipynb'
          ipython 'NeSST Guide.py'